### ISSUE TITLE
Failed to create instance from Template

### ISSUE THREAD

**Issue by graineri** [peterldowns/pgtestdb#14]
Hello! First of all I would like to thank you for this awesome work! It has drastically reduced the time it takes to run our DB tests.

However, and for reasons I still wasn't able to figure out, we sometimes see errors like this while running our tests:
```
failed to create instance: failed to create instance from template testdb_tpl_a2cf4017f6fdb30995f16343e140dbb7: ERROR: source database "testdb_tpl_a2cf4017f6fdb30995f16343e140dbb7" is being accessed by other users (SQLSTATE 55006)
```

Interestingly enough, if I lock the instance creation around a mutex, it still fails.

If we don't run the tests in parallel (i.e. remove all `t.Parallel()`) or change the parallelism flag to something like `-p 2`, it works. 

I'm not sure what could be causing this issue. I tried increasing the number of connections to DB but didn't help.

**Comment by graineri** [comment]
As a workaround, we are recovering from this error and running:
```
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid();
```
Finally, we run `pgtestdb.Custom` again and everything works.

**Comment by graineri** [comment]
Hi Peter! Thanks for your response.

We are using `golangmigrator`. 

We are not able to reproduce this behavior in all of our repos. In particular, we were able to reproduce it in one where we use timescaledb.

**Comment by graineri** [comment]
Thanks so much for your willingness and support, Peter.

Here's the docker-compose we are using:
```
services:
  timescale:
    image: timescale/timescaledb:latest-pg16-bitnami
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_FSYNC: "off"
      POSTGRESQL_SYNCHRONOUS_COMMIT_MODE: "off"
      POSTGRESQL_MAX_CONNECTIONS: 1000
      POSTGRESQL_EXTRA_FLAGS: "-c full_page_writes=off -c shared_buffers=128MB"
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
```

I will try to come up with sample migrations but may take me some time to prepare.

Thanks again!
